/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author HP
 */
public class TelaDeMenuHome extends javax.swing.JFrame {

    /**
     * Creates new form TelaDeMenuHome
     */
    TelaDeRegistarPizza abrirTelaPizza= new TelaDeRegistarPizza();
    TelaDeRegistarSalgados abrirTelaSalgados= new TelaDeRegistarSalgados();
    TelaDeGestaoDeUsuarios abrirTelaUsuario= new TelaDeGestaoDeUsuarios();
    TelaDeVenda abrirTelaVenda= new TelaDeVenda();
    ListarVendas abrirListarVenda= new ListarVendas();
    
    
    public TelaDeMenuHome() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnGerirUsuario = new javax.swing.JButton();
        btnGerirPizza = new javax.swing.JButton();
        btnEfectuarVenda = new javax.swing.JButton();
        btnGerirSalgados = new javax.swing.JButton();
        btnListarVenda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tela de Menu ");

        btnGerirUsuario.setText("1-Gerir Usuarios");
        btnGerirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerirUsuarioActionPerformed(evt);
            }
        });

        btnGerirPizza.setText("2-Gerir Pizza");
        btnGerirPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerirPizzaActionPerformed(evt);
            }
        });

        btnEfectuarVenda.setText("4-Efectuar Venda");
        btnEfectuarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEfectuarVendaActionPerformed(evt);
            }
        });

        btnGerirSalgados.setText("3-Gerir Salgados");
        btnGerirSalgados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerirSalgadosActionPerformed(evt);
            }
        });

        btnListarVenda.setText("Listar Venda");
        btnListarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarVendaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(177, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEfectuarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGerirSalgados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGerirPizza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnGerirUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnListarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))
                        .addGap(150, 150, 150))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(188, 188, 188))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(btnGerirUsuario)
                .addGap(18, 18, 18)
                .addComponent(btnGerirPizza)
                .addGap(18, 18, 18)
                .addComponent(btnGerirSalgados)
                .addGap(21, 21, 21)
                .addComponent(btnEfectuarVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnListarVenda)
                .addContainerGap(60, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerirPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerirPizzaActionPerformed
        // TODO add your handling code here:
        abrirTelaPizza.setVisible(true);
    }//GEN-LAST:event_btnGerirPizzaActionPerformed

    private void btnGerirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerirUsuarioActionPerformed
        abrirTelaUsuario.setVisible(true);
    }//GEN-LAST:event_btnGerirUsuarioActionPerformed

    private void btnEfectuarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEfectuarVendaActionPerformed
        // TODO add your handling code here:
        abrirTelaVenda.setVisible(true);
    }//GEN-LAST:event_btnEfectuarVendaActionPerformed

    private void btnGerirSalgadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerirSalgadosActionPerformed
        // TODO add your handling code here:
        abrirTelaSalgados.setVisible(true);
    }//GEN-LAST:event_btnGerirSalgadosActionPerformed

    private void btnListarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarVendaActionPerformed
        abrirListarVenda.setVisible(true);
    }//GEN-LAST:event_btnListarVendaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeMenuHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeMenuHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeMenuHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeMenuHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeMenuHome().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEfectuarVenda;
    private javax.swing.JButton btnGerirPizza;
    private javax.swing.JButton btnGerirSalgados;
    private javax.swing.JButton btnGerirUsuario;
    private javax.swing.JButton btnListarVenda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
